version: '3'
services:
  simple-server:
    build:
      context: simple-server
    tty: true
    ports:
      - 30000:3000
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./simple-server/app:/app
      - ./simple-server/log:/var/log
      - /app/node_modules
    restart: unless-stopped

