version: '3'
services:
  stub-server:
    build:
      context: stub-server
    tty: true
    ports:
      - 30000:3000
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./stub-server/app:/app
    restart: unless-stopped
