version: '3'
services:
  test-server:
    build:
      context: test-server
    container_name: test_server 
    tty: true
    ports:
      - 3000:3000
    environment:
      TZ: "Asia/Tokyo"
      - ./test-server/app:/app
    restart: unless-stopped
